backend:
  name: git-gateway

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - file: "data/home.yml"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "text" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }